include:
  # CI pipeline is versioned with tags and maintained here:
  # https://gitlab-master.nvidia.com/omniverse/devplat/gitlab/templates/common/kit-extension/
  - project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
    file: 'modules/complete-pipeline.yml'
    ref: v2_latest
  # Compliance
  # See gitlab project environment `Variables` config to see the value of OSEC (compliance) job control booleans.
  # For example OSEC_SONARQUBE_ENABLED, which causes the "osec:sonarqube" job to show up in the pipeline (or not).
  - project: "omniverse/devplat/gitlab/templates/common/compliance"
    file: "modules/omniverse-repo-compliance.gitlab-ci.yml"
    ref: v1_latest

# ==============================================================================================================
# Variables to modify if needed - used in complete-pipeline.yml
variables:
  OMNI_CI_ENABLE_CXX_COVERAGE:
    value: "false"
    description: "Set to true to enable the optional C++ code coverage jobs."
  OSEC_SONARQUBE_ENABLED:
    value: "true"
    description: Enable Sonarcube"
  PLATFORM_LINUX_AARCH64:
    value: "false"
    description: "Set to true to enable the aarch64 platform."
  OFFICIAL_BRANCH_REGEX:
    value: '/^(release\/|feature\/|production\/|public\/).*/'
    description: "Regular expression for release branches"
# ==============================================================================================================
# Gitlab documentation states that the include files are:
# - Merged with those in the .gitlab-ci.yml file.
# - Always evaluated first and then merged with the content of the .gitlab-ci.yml file, regardless of the position of the include keyword.


# ==============================================================================================================
# Publish extensions to the internal registry
#
# All template extensions are packaged into the fat packages, so there's no need to publish them into any registry.
publish-extensions:
  rules:
   - when: never


# ==============================================================================================================
stage-for-github:
  extends:
    - .check-common
    - .runner-utility-linux-x86_64
  allow_failure: true
  script:
    - ./tools/ci/create_source_package.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - _stage/*.tar.xz
      - _stage/*.zip

# ==============================================================================================================
# Disable unused jobs
#

# Disable it because it doesn't work.
# Instead manually update kit sdk version and the version lock `templates/omni.all.template.extensions.kit`.
release-new-version:
  rules:
   - when: never

# we don't have jira tickets!
check-jira-ticket:
  rules:
    - when: never

# ==============================================================================================================
# overrides for osec:sonarqube job
osec:sonarqube:
  variables:
    SONAR_CFAMILY_COMPILE_COMMANDS: _build/linux-x86_64/release/compile_commands.json
    SONAR_EXCLUSIONS: "_build/**,\
      source/tests/**,\
      "
    SONAR_SOURCES: "include,source"
    LINBUILD_EMBEDDED: "1"
  before_script:
    - ./repo.sh schema --config release
    - ./repo.sh build --generate --config release

check-code-format:
  allow_failure: true

.test-common:
  variables:
    OMNI_CAE_PIP_ARCHIVES_DIR: "_build/packages/pip"