apiVersion: v1
kind: Service
metadata:
  name: {{ include "dsx.web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dsx.web.labels" . | nindent 4 }}
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "dsx.web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
