# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "CAE simh"
version = "1.0.1"  # Semantic Versionning is used: https://semver.org/
description = "Extension to support .simh"
category = "CAE"
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "cae", "simh"]  # Search keywords for the Extension Manager
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI

[dependencies]
"omni.cae.data" = {}
"omni.cae.pipapi" = {}
"omni.cae.schema" = {}
"omni.kit.tool.asset_importer" = {}
"omni.cae.file_format.cgns" = {}
"omni.cae.cgns" = {}
"omni.cae.schema.simh" = {}
"omni.client" = {}

[[python.module]]  # Main python module this extension provides, it will be publicly available as "import omni.cae.simh"
name = "omni.cae.simh"
